services:
  auth_service:
    build:
      context: .
      dockerfile: backend/auth_service/Dockerfile
    ports:
      - "8080:8080" # Web UI
    environment:
      - DB_HOST=postgres_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sportsdb
      - DB_PORT=5432
    depends_on:
      - postgres_db

  match_service:
    image: ${DOCKER_REGISTRY-}matchservice
    build:
      context: .
      dockerfile: backend/match_service/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001" # Web UI
    depends_on:
      - postgres_db

  scouting_service:
    image: ${DOCKER_REGISTRY-}scoutingservice
    build:
      context: .
      dockerfile: backend/scouting_service/Dockerfile
    ports:
      - "5002:5002"
      - "5003:5003" # Web UI
    depends_on:
      - postgres_db

  ticket_service:
    image: ${DOCKER_REGISTRY-}ticketservice
    build:
      context: .
      dockerfile: backend/ticket_service/Dockerfile
    ports:
      - "5004:5004"
      - "5005:5005" # Web UI
    depends_on:
      - postgres_db

  travel_service:
    image: ${DOCKER_REGISTRY-}travelservice
    build:
      context: .
      dockerfile: backend/travel_service/Dockerfile
    ports:
      - "5006:5006"
      - "5007:5007" # Web UI
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sportsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  neo4j:
    image: neo4j:5.23
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"   # Web UI
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password 
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - ./database/graph_database/neo4j_init.cql:/docker-entrypoint-initdb.d/neo4j_init.cql

  neo4j-init:
    image: neo4j:5.23
    depends_on:
      - neo4j
    volumes:
      - ./database/graph_database/neo4j_init.cql:/neo4j_init.cql
    entrypoint: >
      bash -c "
        echo 'Waiting for Neo4j...';
        until cypher-shell -u neo4j -p password -a bolt://neo4j:7687 'RETURN 1'; do
          sleep 3;
        done;
        echo 'Running init script...';
        cypher-shell -u neo4j -p password -a bolt://neo4j:7687 -f /neo4j_init.cql;
        echo 'Seeding finished.';
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.vite
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  pgdata:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
