-- Generated by Oracle SQL Developer Data Modeler 24.3.0.240.1210
--   at:        2025-08-31 23:26:04 CEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



DROP TABLE IF EXISTS accommodation_offer CASCADE;

DROP TABLE IF EXISTS accommodation_request CASCADE;

DROP TABLE IF EXISTS agency CASCADE;

DROP TABLE IF EXISTS automatic_recommendations CASCADE;

DROP TABLE IF EXISTS cart CASCADE;

DROP TABLE IF EXISTS cart_item CASCADE;

DROP TABLE IF EXISTS competition CASCADE;

DROP TABLE IF EXISTS credit_card CASCADE;

DROP TABLE IF EXISTS general_event CASCADE;

DROP TABLE IF EXISTS individual_ticket CASCADE;

DROP TABLE IF EXISTS management CASCADE;

DROP TABLE IF EXISTS management_member_request CASCADE;

DROP TABLE IF EXISTS match CASCADE;

DROP TABLE IF EXISTS match_tracking CASCADE;

DROP TABLE IF EXISTS metric_type CASCADE;

DROP TABLE IF EXISTS metrics CASCADE;

DROP TABLE IF EXISTS nationality CASCADE;

DROP TABLE IF EXISTS offer CASCADE;

DROP TABLE IF EXISTS personal_event CASCADE;

DROP TABLE IF EXISTS physical_metrics CASCADE;

DROP TABLE IF EXISTS player CASCADE;

DROP TABLE IF EXISTS position CASCADE;

DROP TABLE IF EXISTS purchase_offer CASCADE;

DROP TABLE IF EXISTS request CASCADE;

DROP TABLE IF EXISTS season CASCADE;

DROP TABLE IF EXISTS season_metrics CASCADE;

DROP TABLE IF EXISTS season_ticket CASCADE;

DROP TABLE IF EXISTS seat CASCADE;

DROP TABLE IF EXISTS sent_request CASCADE;

DROP TABLE IF EXISTS "session" CASCADE;

DROP TABLE IF EXISTS session_metrics CASCADE;

DROP TABLE IF EXISTS session_status CASCADE;

DROP TABLE IF EXISTS session_type CASCADE;

DROP TABLE IF EXISTS team CASCADE;

DROP TABLE IF EXISTS team_event CASCADE;

DROP TABLE IF EXISTS team_member CASCADE;

DROP TABLE IF EXISTS team_member_match CASCADE;

DROP TABLE IF EXISTS team_member_request CASCADE;

DROP TABLE IF EXISTS ticket_price_parameter CASCADE;

DROP TABLE IF EXISTS transportation_offer CASCADE;

DROP TABLE IF EXISTS transportation_request CASCADE;

DROP TABLE IF EXISTS travel_information CASCADE;

DROP TABLE IF EXISTS trip CASCADE;

DROP TABLE IF EXISTS "users" CASCADE;

DROP TABLE IF EXISTS visa CASCADE;

DROP TABLE IF EXISTS zone CASCADE;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE accommodation_offer (
    id_offer       INTEGER NOT NULL,
    name           VARCHAR(255),
    capacity       INTEGER,
    type           VARCHAR(20),
    id_agency      INTEGER NOT NULL,
    id_request     INTEGER NOT NULL,
    double_room    INTEGER,
    triple_room    INTEGER,
    quadruple_room INTEGER,
    breakfast      INTEGER,
    fitness_center INTEGER,
    pool           INTEGER,
    wifi           INTEGER,
    spa            INTEGER
);

ALTER TABLE accommodation_offer
    ADD
        CHECK ( type IN ( 'hotel', 'house', 'villa' ) );

ALTER TABLE accommodation_offer
    ADD CONSTRAINT accommodation_offer_pk PRIMARY KEY ( id_offer,
                                                        id_agency,
                                                        id_request );

CREATE TABLE accommodation_request (
    id_request       INTEGER NOT NULL,
    number_of_guests INTEGER,
    number_of_rooms  INTEGER,
    check_in_date    DATE,
    check_out_date   DATE,
    type             VARCHAR(20)
);

ALTER TABLE accommodation_request
    ADD
        CHECK ( type IN ( 'hotel', 'house', 'villa' ) );

ALTER TABLE accommodation_request ADD CONSTRAINT accommodation_request_pk PRIMARY KEY ( id_request );

CREATE TABLE agency (
    id_agency INTEGER NOT NULL,
    name      VARCHAR(255),
    email     VARCHAR(255),
    type      VARCHAR(20)
);

ALTER TABLE agency
    ADD CHECK ( type IN ( 'accommodation', 'transportation' ) );

ALTER TABLE agency ADD CONSTRAINT agency_pk PRIMARY KEY ( id_agency );

CREATE TABLE automatic_recommendations (
    priority      VARCHAR(20),
    status        VARCHAR(20),
    creation_time DATE,
    id_match      INTEGER NOT NULL
);

ALTER TABLE automatic_recommendations
    ADD
        CHECK ( priority IN ( 'medium priority', 'not priority', 'urgent' ) );

ALTER TABLE automatic_recommendations
    ADD CHECK ( status IN ( 'accepted', 'rejected' ) );

ALTER TABLE automatic_recommendations ADD CONSTRAINT automatic_recommendations_pk PRIMARY KEY ( id_match );

CREATE TABLE cart (
    id_cart        INTEGER NOT NULL,
    created_at     DATE,
    items_number   INTEGER,
    status         VARCHAR(255),
    id_credit_card INTEGER,
    id_user        INTEGER NOT NULL
);

ALTER TABLE cart ADD CONSTRAINT cart_pk PRIMARY KEY ( id_cart );

CREATE TABLE cart_item (
    id_cart           INTEGER NOT NULL,
    id_purchase_offer INTEGER NOT NULL,
    added_at          DATE,
    quantity          INTEGER
);

ALTER TABLE cart_item ADD CONSTRAINT cart_item_pk PRIMARY KEY ( id_cart,
                                                                id_purchase_offer );

CREATE TABLE competition (
    id_competition    INTEGER NOT NULL,
    name              VARCHAR(50),
    started_at        DATE,
    ended_at          DATE,
    number_of_matches INTEGER
);

ALTER TABLE competition ADD CONSTRAINT competition_pk PRIMARY KEY ( id_competition );

CREATE TABLE credit_card (
    id_credit_card INTEGER NOT NULL,
    created_at     DATE,
    number       VARCHAR(16),
    cvv            INTEGER,
    name           VARCHAR(50),
    id_user        INTEGER NOT NULL
);

ALTER TABLE credit_card ADD CONSTRAINT credit_card_pk PRIMARY KEY ( id_credit_card );

CREATE TABLE general_event (
    id_event      INTEGER NOT NULL,
    creation_time DATE,
    notes         VARCHAR(255),
    role          VARCHAR(20),
    type          VARCHAR(20),
    id_match      INTEGER NOT NULL
);

ALTER TABLE general_event
    ADD
        CHECK ( role IN ( 'general', 'personal', 'team' ) );

ALTER TABLE general_event
    ADD
        CHECK ( type IN ( 'break end', 'break start', 'other', 'pause end', 'pause start',
                          'period end', 'period start' ) );

ALTER TABLE general_event ADD CONSTRAINT general_event_pk PRIMARY KEY ( id_event );

CREATE TABLE individual_ticket (
    id_purchase_offer    INTEGER NOT NULL,
    id_match             INTEGER NOT NULL,
    id_individual_ticket INTEGER NOT NULL
);

ALTER TABLE individual_ticket ADD CONSTRAINT individual_ticket_pk PRIMARY KEY ( id_purchase_offer );

ALTER TABLE individual_ticket ADD CONSTRAINT individual_ticket_pkv1 UNIQUE ( id_individual_ticket );

CREATE TABLE management (
    member_id      INTEGER NOT NULL,
    member_name    VARCHAR(255),
    member_surname VARCHAR(255),
    member_role    VARCHAR(20)
);

ALTER TABLE management
    ADD
        CHECK ( member_role IN ( 'assistant coach', 'coach', 'doctor', 'other', 'therapist' ) );

ALTER TABLE management ADD CONSTRAINT management_pk PRIMARY KEY ( member_id );

CREATE TABLE management_member_request (
    id_request           INTEGER NOT NULL,
    id_management_member INTEGER NOT NULL
);

ALTER TABLE management_member_request ADD CONSTRAINT management_member_request_pk PRIMARY KEY ( id_request,
                                                                                                id_management_member );

CREATE TABLE match (
    id_match                INTEGER NOT NULL,
    name                    VARCHAR(255),
    created_at              DATE,
    type                    VARCHAR(20),
    state                   VARCHAR(255),
    city                    VARCHAR(255),
    hall                    VARCHAR(255),
    is_in_our_hall          INTEGER,
    transportation_required INTEGER,
    accommodation_required  INTEGER,
    id_competition          INTEGER,
    id_season               INTEGER NOT NULL,
    id_team                 INTEGER NOT NULL
);

ALTER TABLE match
    ADD CHECK ( type IN ( 'away', 'home' ) );

ALTER TABLE match ADD CONSTRAINT match_pk PRIMARY KEY ( id_match );

CREATE TABLE match_tracking (
    start_time                 DATE,
    end_time                   DATE,
    tracking_status            VARCHAR(20),
    period_duration            INTEGER,
    current_period             VARCHAR(20),
    period_status              VARCHAR(20),
    period_start_time          DATE,
    elapsed_period_time        INTEGER,
    last_pause_start_time      DATE,
    total_pause_time_in_period INTEGER,
    last_update_time           DATE,
    our_points                 INTEGER,
    opponent_points            INTEGER,
    id_user                    INTEGER,
    id_match                   INTEGER NOT NULL
);

ALTER TABLE match_tracking
    ADD
        CHECK ( tracking_status IN ( 'active', 'finished', 'preparation' ) );

ALTER TABLE match_tracking
    ADD
        CHECK ( current_period IN ( '1', '2', '3', '4', 'end' ) );

ALTER TABLE match_tracking
    ADD
        CHECK ( period_status IN ( 'active', 'finished', 'paused' ) );

CREATE UNIQUE INDEX match_tracking__idx ON
    match_tracking (
        id_user
    ASC );

ALTER TABLE match_tracking ADD CONSTRAINT match_tracking_pk PRIMARY KEY ( id_match );

CREATE TABLE metric_type (
    id_type INTEGER NOT NULL,
    type    VARCHAR(255)
);

ALTER TABLE metric_type ADD CONSTRAINT metric_type_pk PRIMARY KEY ( id_type );

CREATE TABLE metrics (
    id_metrics     INTEGER NOT NULL,
    name           VARCHAR(255),
    is_permanent   INTEGER,
    metric_weight  INTEGER,
    id_user        INTEGER NOT NULL,
    id_metric_type INTEGER NOT NULL
);

CREATE UNIQUE INDEX metrics__idx ON
    metrics (
        id_user
    ASC );

ALTER TABLE metrics ADD CONSTRAINT metrics_pk PRIMARY KEY ( id_metrics );

CREATE TABLE nationality (
    id_nationality INTEGER NOT NULL,
    state          VARCHAR(255)
);

ALTER TABLE nationality ADD CONSTRAINT nationality_pk PRIMARY KEY ( id_nationality );

CREATE TABLE offer (
    id_offer     INTEGER NOT NULL,
    price        INTEGER,
    user_id_user INTEGER,
    id_match     INTEGER NOT NULL,
    id_agency    INTEGER NOT NULL,
    id_request   INTEGER NOT NULL,
    type         VARCHAR(20)
);

ALTER TABLE offer
    ADD CHECK ( type IN ( 'accommodation', 'transportation' ) );

--  ERROR: No Discriminator Column found in Arc FKArc_1 - check constraint cannot be generated

ALTER TABLE offer
    ADD CONSTRAINT offer_pk PRIMARY KEY ( id_offer,
                                          id_agency,
                                          id_request );

CREATE TABLE personal_event (
    id_event      INTEGER NOT NULL,
    creation_time DATE,
    notes         VARCHAR(255),
    role          VARCHAR(20),
    type          VARCHAR(20),
    id_team       INTEGER NOT NULL,
    id_player     INTEGER NOT NULL,
    id_match      INTEGER NOT NULL
);

ALTER TABLE personal_event
    ADD
        CHECK ( role IN ( 'general', 'personal', 'team' ) );

ALTER TABLE personal_event
    ADD
        CHECK ( type IN ( '+2p', '+3p', '+ft', '2p', '3p',
                          'assist', 'block', 'foul', 'ft', 'other',
                          'reb def', 'reb of', 'steal', 'substitution in', 'substitution out' ) );

ALTER TABLE personal_event ADD CONSTRAINT personal_event_pk PRIMARY KEY ( id_event );

CREATE TABLE physical_metrics (
    id_physical_metrics INTEGER NOT NULL,
    vertical_jump       INTEGER,
    fat_percentage      INTEGER,
    bench_press_weight  INTEGER,
    squat_weight        INTEGER,
    sprint_speed        INTEGER,
    weight              INTEGER,
    height              INTEGER,
    wingspan            INTEGER,
    date_of_measurement DATE,
    id_player           INTEGER NOT NULL
);

ALTER TABLE physical_metrics ADD CONSTRAINT physical_metrics_pk PRIMARY KEY ( id_physical_metrics );

CREATE TABLE player (
    id_player      INTEGER NOT NULL,
    name           VARCHAR(255),
    surname        VARCHAR(255),
    birthday       DATE,
    id_nationality INTEGER NOT NULL,
    id_position    INTEGER NOT NULL
);

ALTER TABLE player ADD CONSTRAINT player_pk PRIMARY KEY ( id_player );

CREATE TABLE position (
    id_position INTEGER NOT NULL,
    name        VARCHAR(20)
);

ALTER TABLE position ADD CONSTRAINT position_pk PRIMARY KEY ( id_position );

CREATE TABLE purchase_offer (
    id_purchase_offer INTEGER NOT NULL,
    name              VARCHAR(255),
    description       VARCHAR(255),
    type              VARCHAR(50),
    status            VARCHAR(255),
    released_at       DATE,
    created_at        DATE,
    expires_at        DATE,
    id_seat           INTEGER NOT NULL
);

ALTER TABLE purchase_offer
    ADD CHECK ( type IN ( 'individual ticket', 'season ticket' ) );

ALTER TABLE purchase_offer ADD CONSTRAINT purchase_offer_pk PRIMARY KEY ( id_purchase_offer );

CREATE TABLE request (
    id_request INTEGER NOT NULL,
    state      VARCHAR(255),
    city       VARCHAR(255),
    hall       VARCHAR(255),
    budget     INTEGER,
    id_match   INTEGER NOT NULL,
    type       VARCHAR(20)
);

ALTER TABLE request
    ADD CHECK ( type IN ( 'accommodation', 'transportation' ) );

--  ERROR: No Discriminator Column found in Arc FKArc_2 - check constraint cannot be generated

ALTER TABLE request ADD CONSTRAINT request_pk PRIMARY KEY ( id_request );

CREATE TABLE season (
    id_season  INTEGER NOT NULL,
    started_at DATE,
    ended_at   DATE,
    name       VARCHAR(255)
);

ALTER TABLE season ADD CONSTRAINT season_pk PRIMARY KEY ( id_season );

CREATE TABLE season_metrics (
    id_season  INTEGER NOT NULL,
    id_metrics INTEGER NOT NULL
);

ALTER TABLE season_metrics ADD CONSTRAINT season_metrics_pk PRIMARY KEY ( id_season,
                                                                          id_metrics );

CREATE TABLE season_ticket (
    id_purchase_offer              INTEGER NOT NULL,
    id_season                      INTEGER NOT NULL,
    fixed_promotional_ticket_price INTEGER
);

ALTER TABLE season_ticket ADD CONSTRAINT season_ticket_pk PRIMARY KEY ( id_purchase_offer );

CREATE TABLE seat (
    id_seat   INTEGER NOT NULL,
    "row"     INTEGER,
    number  INTEGER,
    type      VARCHAR(255),
    direction VARCHAR(255),
    status    VARCHAR(255),
    id_zone   INTEGER
);

ALTER TABLE seat ADD CONSTRAINT seat_pk PRIMARY KEY ( id_seat );

CREATE TABLE sent_request (
    id_agency  INTEGER NOT NULL,
    id_request INTEGER NOT NULL
);

ALTER TABLE sent_request ADD CONSTRAINT sent_request_pk PRIMARY KEY ( id_agency,
                                                                      id_request );

CREATE TABLE "session" (
    id_session        INTEGER NOT NULL,
    start_time        DATE,
    end_time          DATE,
    id_session_status INTEGER NOT NULL,
    id_session_type   INTEGER NOT NULL,
    id_user           INTEGER NOT NULL,
    id_player         INTEGER NOT NULL
);

ALTER TABLE "session" ADD CONSTRAINT session_pk PRIMARY KEY ( id_session );

CREATE TABLE session_metrics (
    value      VARCHAR(255),
    id_session INTEGER NOT NULL,
    id_metrics INTEGER NOT NULL
);

ALTER TABLE session_metrics ADD CONSTRAINT session_metrics_pk PRIMARY KEY ( id_metrics,
                                                                            id_session );

CREATE TABLE session_status (
    id_status INTEGER NOT NULL,
    status    VARCHAR(255)
);

ALTER TABLE session_status ADD CONSTRAINT session_status_pk PRIMARY KEY ( id_status );

CREATE TABLE session_type (
    id_type INTEGER NOT NULL,
    type    VARCHAR(255)
);

ALTER TABLE session_type ADD CONSTRAINT session_type_pk PRIMARY KEY ( id_type );

CREATE TABLE team (
    id_team        INTEGER NOT NULL,
    name           VARCHAR(255),
    state          VARCHAR(255),
    city           VARCHAR(255),
    hall           VARCHAR(255),
    founded_date   DATE,
    coach          VARCHAR(255),
    key_strenghts  VARCHAR(255),
    key_weaknesses VARCHAR(255)
);

ALTER TABLE team ADD CONSTRAINT team_pk PRIMARY KEY ( id_team );

CREATE TABLE team_event (
    id_event      INTEGER NOT NULL,
    creation_time DATE,
    notes         VARCHAR(255),
    role          VARCHAR(20),
    type          VARCHAR(20),
    id_team       INTEGER NOT NULL,
    id_match      INTEGER NOT NULL
);

ALTER TABLE team_event
    ADD
        CHECK ( role IN ( 'general', 'personal', 'team' ) );

ALTER TABLE team_event
    ADD
        CHECK ( type IN ( 'other', 'technical foul', 'timeout' ) );

ALTER TABLE team_event ADD CONSTRAINT team_event_pk PRIMARY KEY ( id_event );

CREATE TABLE team_member (
    jersey_number INTEGER,
    captain       INTEGER,
    status        VARCHAR(20),
    id_player     INTEGER NOT NULL,
    id_team       INTEGER NOT NULL
);

ALTER TABLE team_member
    ADD
        CHECK ( status IN ( 'active', 'injured', 'suspended' ) );

ALTER TABLE team_member ADD CONSTRAINT team_member_pk PRIMARY KEY ( id_team,
                                                                    id_player );

CREATE TABLE team_member_match (
    starting_lineup INTEGER,
    in_game         INTEGER,
    id_team         INTEGER NOT NULL,
    id_player       INTEGER NOT NULL,
    id_match        INTEGER NOT NULL
);

ALTER TABLE team_member_match
    ADD CONSTRAINT team_member_match_pk PRIMARY KEY ( id_match,
                                                      id_team,
                                                      id_player );

CREATE TABLE team_member_request (
    id_team    INTEGER NOT NULL,
    id_player  INTEGER NOT NULL,
    id_request INTEGER NOT NULL
);

ALTER TABLE team_member_request
    ADD CONSTRAINT team_member_request_pk PRIMARY KEY ( id_team,
                                                        id_player,
                                                        id_request );

CREATE TABLE ticket_price_parameter (
    id_ticket_price_parameter INTEGER NOT NULL,
    price_factor              INTEGER,
    time_factor               INTEGER,
    minimum_seat_price        INTEGER,
    maximum_seat_price        INTEGER,
    id_user                   INTEGER NOT NULL,
    id_zone                   INTEGER NOT NULL,
    id_match                  INTEGER NOT NULL
);

ALTER TABLE ticket_price_parameter ADD CONSTRAINT ticket_price_parameter_pk PRIMARY KEY ( id_ticket_price_parameter );

CREATE TABLE transportation_offer (
    id_offer         INTEGER NOT NULL,
    company_name     VARCHAR(255),
    capacity         INTEGER,
    type             VARCHAR(20),
    id_agency        INTEGER NOT NULL,
    id_request       INTEGER NOT NULL,
    equipment_space  INTEGER,
    air_conditioning INTEGER,
    tv               INTEGER,
    wifi             INTEGER,
    restroom         INTEGER
);

ALTER TABLE transportation_offer
    ADD
        CHECK ( type IN ( 'autobus', 'plane', 'train', 'van' ) );

ALTER TABLE transportation_offer
    ADD CONSTRAINT transportation_offer_pk PRIMARY KEY ( id_offer,
                                                         id_agency,
                                                         id_request );

CREATE TABLE transportation_request (
    id_request           INTEGER NOT NULL,
    number_of_passengers INTEGER,
    start_date           DATE,
    end_date             DATE,
    vehicle_type         VARCHAR(20)
);

ALTER TABLE transportation_request
    ADD
        CHECK ( vehicle_type IN ( 'autobus', 'plane', 'train', 'van' ) );

ALTER TABLE transportation_request ADD CONSTRAINT transportation_request_pk PRIMARY KEY ( id_request );

CREATE TABLE travel_information (
    id_travel_information    INTEGER NOT NULL,
    passport_number          VARCHAR(30),
    passport_expiration_date DATE,
    nationality              VARCHAR(255),
    phone                    VARCHAR(20),
    email                    VARCHAR(50),
    role                     VARCHAR(20),
    id_management_member     INTEGER,
    id_team                  INTEGER,
    id_player                INTEGER
);

ALTER TABLE travel_information
    ADD CHECK ( role IN ( 'management', 'player' ) );

ALTER TABLE travel_information ADD CONSTRAINT travel_information_pk PRIMARY KEY ( id_travel_information );

ALTER TABLE travel_information ADD CONSTRAINT travel_information_pkv1 UNIQUE ( id_team,
                                                                               id_player );

ALTER TABLE travel_information ADD CONSTRAINT travel_information_pkv2 UNIQUE ( id_management_member );

CREATE TABLE trip (
    id_trip                   INTEGER NOT NULL,
    notes                     VARCHAR(255),
    match_id_match            INTEGER NOT NULL,
    id_accommodation_offer    INTEGER,
    id_transportation_offer   INTEGER,
    id_accommodation_agency   INTEGER,
    id_transportation_agency  INTEGER,
    id_accommodation_request  INTEGER,
    id_transportation_request INTEGER
);

CREATE UNIQUE INDEX trip__idx ON
    trip (
        match_id_match
    ASC );

CREATE UNIQUE INDEX trip__idxv1 ON
    trip (
        id_accommodation_offer
    ASC,
        id_accommodation_agency
    ASC,
        id_accommodation_request
    ASC );

CREATE UNIQUE INDEX trip__idxv2 ON
    trip (
        id_transportation_offer
    ASC,
        id_transportation_agency
    ASC,
        id_transportation_request
    ASC );

ALTER TABLE trip ADD CONSTRAINT trip_pk PRIMARY KEY ( id_trip );

CREATE TABLE "users" (
    id_user  SERIAL NOT NULL,
    name     VARCHAR(50),
    surname  VARCHAR(50),
    email    VARCHAR(50),
    phone    VARCHAR(20),
    password VARCHAR(255),
    type     VARCHAR(50)
);

ALTER TABLE "users" ADD CONSTRAINT user_pk PRIMARY KEY ( id_user );

CREATE TABLE visa (
    visa_number           VARCHAR(20) NOT NULL,
    state                 VARCHAR(255),
    creation_date         DATE,
    expiration_date       DATE,
    id_travel_information INTEGER NOT NULL
);

ALTER TABLE visa ADD CONSTRAINT visa_pk PRIMARY KEY ( visa_number );

CREATE TABLE zone (
    id_zone          INTEGER NOT NULL,
    name             VARCHAR(255),
    rank             INTEGER,
    maximum_capacity INTEGER,
    status           VARCHAR(255)
);

ALTER TABLE zone ADD CONSTRAINT zone_pk PRIMARY KEY ( id_zone );

ALTER TABLE accommodation_offer
    ADD CONSTRAINT accommodation_offer_offer_fk
        FOREIGN KEY ( id_offer,
                      id_agency,
                      id_request )
            REFERENCES offer ( id_offer,
                               id_agency,
                               id_request );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE accommodation_request
    ADD CONSTRAINT accommodation_request_request_fk FOREIGN KEY ( id_request )
        REFERENCES request ( id_request );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE automatic_recommendations
    ADD CONSTRAINT automatic_recommendations_match_tracking_fk FOREIGN KEY ( id_match )
        REFERENCES match_tracking ( id_match );

ALTER TABLE cart
    ADD CONSTRAINT cart_credit_card_fk FOREIGN KEY ( id_credit_card )
        REFERENCES credit_card ( id_credit_card );

ALTER TABLE cart_item
    ADD CONSTRAINT cart_item_cart_fk FOREIGN KEY ( id_cart )
        REFERENCES cart ( id_cart );

ALTER TABLE cart_item
    ADD CONSTRAINT cart_item_purchase_offer_fk FOREIGN KEY ( id_purchase_offer )
        REFERENCES purchase_offer ( id_purchase_offer );

ALTER TABLE cart
    ADD CONSTRAINT cart_user_fk FOREIGN KEY ( id_user )
        REFERENCES "users" ( id_user );

ALTER TABLE credit_card
    ADD CONSTRAINT credit_card_user_fk FOREIGN KEY ( id_user )
        REFERENCES "users" ( id_user );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE general_event
    ADD CONSTRAINT general_event_match_tracking_fk FOREIGN KEY ( id_match )
        REFERENCES match_tracking ( id_match );

ALTER TABLE individual_ticket
    ADD CONSTRAINT individual_ticket_match_fk FOREIGN KEY ( id_match )
        REFERENCES match ( id_match );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE management_member_request
    ADD CONSTRAINT management_member_request_management_fk FOREIGN KEY ( id_management_member )
        REFERENCES management ( member_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE management_member_request
    ADD CONSTRAINT management_member_request_request_fk FOREIGN KEY ( id_request )
        REFERENCES request ( id_request );

ALTER TABLE match
    ADD CONSTRAINT match_competition_fk FOREIGN KEY ( id_competition )
        REFERENCES competition ( id_competition );

ALTER TABLE match
    ADD CONSTRAINT match_season_fk FOREIGN KEY ( id_season )
        REFERENCES season ( id_season );

ALTER TABLE match
    ADD CONSTRAINT match_team_fk FOREIGN KEY ( id_team )
        REFERENCES team ( id_team );

ALTER TABLE match_tracking
    ADD CONSTRAINT match_tracking_match_fk FOREIGN KEY ( id_match )
        REFERENCES match ( id_match );

ALTER TABLE match_tracking
    ADD CONSTRAINT match_tracking_user_fk FOREIGN KEY ( id_user )
        REFERENCES "users" ( id_user );

ALTER TABLE metrics
    ADD CONSTRAINT metrics_metric_type_fk FOREIGN KEY ( id_metric_type )
        REFERENCES metric_type ( id_type );

ALTER TABLE metrics
    ADD CONSTRAINT metrics_user_fk FOREIGN KEY ( id_user )
        REFERENCES "users" ( id_user );

ALTER TABLE offer
    ADD CONSTRAINT offer_match_fk FOREIGN KEY ( id_match )
        REFERENCES match ( id_match );

ALTER TABLE offer
    ADD CONSTRAINT offer_sent_request_fk
        FOREIGN KEY ( id_agency,
                      id_request )
            REFERENCES sent_request ( id_agency,
                                      id_request );

ALTER TABLE offer
    ADD CONSTRAINT offer_user_fk FOREIGN KEY ( user_id_user )
        REFERENCES "users" ( id_user );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE personal_event
    ADD CONSTRAINT personal_event_match_tracking_fk FOREIGN KEY ( id_match )
        REFERENCES match_tracking ( id_match );

ALTER TABLE personal_event
    ADD CONSTRAINT personal_event_team_member_fk
        FOREIGN KEY ( id_team,
                      id_player )
            REFERENCES team_member ( id_team,
                                     id_player );

ALTER TABLE physical_metrics
    ADD CONSTRAINT physical_metrics_player_fk FOREIGN KEY ( id_player )
        REFERENCES player ( id_player );

ALTER TABLE player
    ADD CONSTRAINT player_nationality_fk FOREIGN KEY ( id_nationality )
        REFERENCES nationality ( id_nationality );

ALTER TABLE player
    ADD CONSTRAINT player_position_fk FOREIGN KEY ( id_position )
        REFERENCES position ( id_position );

ALTER TABLE purchase_offer
    ADD CONSTRAINT purchase_offer_seat_fk FOREIGN KEY ( id_seat )
        REFERENCES seat ( id_seat );

ALTER TABLE request
    ADD CONSTRAINT request_match_fk FOREIGN KEY ( id_match )
        REFERENCES match ( id_match );

ALTER TABLE season_metrics
    ADD CONSTRAINT season_metrics_metrics_fk FOREIGN KEY ( id_metrics )
        REFERENCES metrics ( id_metrics );

ALTER TABLE season_metrics
    ADD CONSTRAINT season_metrics_season_fk FOREIGN KEY ( id_season )
        REFERENCES season ( id_season );

ALTER TABLE season_ticket
    ADD CONSTRAINT season_ticket_season_fk FOREIGN KEY ( id_season )
        REFERENCES season ( id_season );

ALTER TABLE seat
    ADD CONSTRAINT seat_zone_fk FOREIGN KEY ( id_zone )
        REFERENCES zone ( id_zone );

ALTER TABLE sent_request
    ADD CONSTRAINT sent_request_agency_fk FOREIGN KEY ( id_agency )
        REFERENCES agency ( id_agency );

ALTER TABLE sent_request
    ADD CONSTRAINT sent_request_request_fk FOREIGN KEY ( id_request )
        REFERENCES request ( id_request );

ALTER TABLE session_metrics
    ADD CONSTRAINT session_metrics_metrics_fk FOREIGN KEY ( id_metrics )
        REFERENCES metrics ( id_metrics );

ALTER TABLE session_metrics
    ADD CONSTRAINT session_metrics_session_fk FOREIGN KEY ( id_session )
        REFERENCES "session" ( id_session );

ALTER TABLE "session"
    ADD CONSTRAINT session_player_fk FOREIGN KEY ( id_player )
        REFERENCES player ( id_player );

ALTER TABLE "session"
    ADD CONSTRAINT session_session_status_fk FOREIGN KEY ( id_session_status )
        REFERENCES session_status ( id_status );

ALTER TABLE "session"
    ADD CONSTRAINT session_session_type_fk FOREIGN KEY ( id_session_type )
        REFERENCES session_type ( id_type );

ALTER TABLE "session"
    ADD CONSTRAINT session_user_fk FOREIGN KEY ( id_user )
        REFERENCES "users" ( id_user );

ALTER TABLE team_event
    ADD CONSTRAINT team_event_match_tracking_fk FOREIGN KEY ( id_match )
        REFERENCES match_tracking ( id_match );

ALTER TABLE team_event
    ADD CONSTRAINT team_event_team_fk FOREIGN KEY ( id_team )
        REFERENCES team ( id_team );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE team_member_match
    ADD CONSTRAINT team_member_match_match_tracking_fk FOREIGN KEY ( id_match )
        REFERENCES match_tracking ( id_match );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE team_member_match
    ADD CONSTRAINT team_member_match_team_member_fk
        FOREIGN KEY ( id_team,
                      id_player )
            REFERENCES team_member ( id_team,
                                     id_player );

ALTER TABLE team_member
    ADD CONSTRAINT team_member_player_fk FOREIGN KEY ( id_player )
        REFERENCES player ( id_player );

ALTER TABLE team_member_request
    ADD CONSTRAINT team_member_request_request_fk FOREIGN KEY ( id_request )
        REFERENCES request ( id_request );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE team_member_request
    ADD CONSTRAINT team_member_request_team_member_fk
        FOREIGN KEY ( id_team,
                      id_player )
            REFERENCES team_member ( id_team,
                                     id_player );

ALTER TABLE team_member
    ADD CONSTRAINT team_member_team_fk FOREIGN KEY ( id_team )
        REFERENCES team ( id_team );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE ticket_price_parameter
    ADD CONSTRAINT ticket_price_parameter_match_fk FOREIGN KEY ( id_match )
        REFERENCES match ( id_match );

ALTER TABLE ticket_price_parameter
    ADD CONSTRAINT ticket_price_parameter_user_fk FOREIGN KEY ( id_user )
        REFERENCES "users" ( id_user );

ALTER TABLE ticket_price_parameter
    ADD CONSTRAINT ticket_price_parameter_zone_fk FOREIGN KEY ( id_zone )
        REFERENCES zone ( id_zone );

ALTER TABLE transportation_offer
    ADD CONSTRAINT transportation_offer_offer_fk
        FOREIGN KEY ( id_offer,
                      id_agency,
                      id_request )
            REFERENCES offer ( id_offer,
                               id_agency,
                               id_request );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE transportation_request
    ADD CONSTRAINT transportation_request_request_fk FOREIGN KEY ( id_request )
        REFERENCES request ( id_request );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE travel_information
    ADD CONSTRAINT travel_information_management_fk FOREIGN KEY ( id_management_member )
        REFERENCES management ( member_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE travel_information
    ADD CONSTRAINT travel_information_team_member_fk
        FOREIGN KEY ( id_team,
                      id_player )
            REFERENCES team_member ( id_team,
                                     id_player );

ALTER TABLE trip
    ADD CONSTRAINT trip_accommodation_offer_fk
        FOREIGN KEY ( id_accommodation_offer,
                      id_accommodation_agency,
                      id_accommodation_request )
            REFERENCES accommodation_offer ( id_offer,
                                             id_agency,
                                             id_request );

ALTER TABLE trip
    ADD CONSTRAINT trip_match_fk FOREIGN KEY ( match_id_match )
        REFERENCES match ( id_match );

ALTER TABLE trip
    ADD CONSTRAINT trip_transportation_offer_fk
        FOREIGN KEY ( id_transportation_offer,
                      id_transportation_agency,
                      id_transportation_request )
            REFERENCES transportation_offer ( id_offer,
                                              id_agency,
                                              id_request );

ALTER TABLE visa
    ADD CONSTRAINT visa_travel_information_fk FOREIGN KEY ( id_travel_information )
        REFERENCES travel_information ( id_travel_information );

--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated

--  ERROR: No Discriminator Column found in Arc FKArc_2 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_2 - constraint trigger for Arc cannot be generated



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            46
-- CREATE INDEX                             5
-- ALTER TABLE                            132
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE -- CREATE USER                              0
-- 
-- DROP -- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS SCHEMA                       0
-- ORDS OBJECT                       0
-- 
-- ERRORS                                  19
-- WARNINGS                                 0
